version: "3.8"

services:
  nginx-certbot:
    container_name: video-nginx
    image: christiankriedemann/video-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/conf:/etc/nginx/conf.d
      - ./data/nginx/cache:/var/cache/nginx
      - ./data/nginx/log:/var/log/nginx
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/www:/var/www
    network_mode: "host"
    restart: unless-stopped
    user: "root:root"
